//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishInABox.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MARINE_SPECIES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MARINE_SPECIES()
        {
            this.RECORD_PET = new HashSet<RECORD_PET>();
            this.TANK_LOG = new HashSet<TANK_LOG>();
        }
    
        public int ID_PK { get; set; }
        [Display(Name = "Marine Classification")]
        public int CLASS_FK { get; set; }
        [Display(Name = "MPI Species ID")]
        public int SPECIES_FK { get; set; }
        [Display(Name = "Scientific Name")]
        public string SCIENTIFIC { get; set; }
        [Display(Name = "Common Name")]
        public string COMMON { get; set; }
        [Display(Name = "Cam's Terminology")]
        public string TEXT { get; set; }
        [Display(Name = "MPI Record Fag")]
        public bool FLAG { get; set; }
        public Nullable<int> FAMILY_FK { get; set; }
    
        public virtual MARINE_CLASS MARINE_CLASS { get; set; }
        public virtual MARINE_FAMILY MARINE_FAMILY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECORD_PET> RECORD_PET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TANK_LOG> TANK_LOG { get; set; }
    }
}
