//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishInABox.Models.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fishinaboxEntities : DbContext
    {
        public fishinaboxEntities()
            : base("name=fishinaboxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MARINE_CLASS> MARINE_CLASS { get; set; }
        public virtual DbSet<MARINE_FAMILY> MARINE_FAMILY { get; set; }
        public virtual DbSet<MARINE_SPECIES> MARINE_SPECIES { get; set; }
        public virtual DbSet<RECORD_PET_SIZE> RECORD_PET_SIZE { get; set; }
        public virtual DbSet<RECORD_GROUP> RECORD_GROUP { get; set; }
        public virtual DbSet<RECORD_PET> RECORD_PET { get; set; }
    }
}
