//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishInABox.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIPMENT_ITEM
    {
        public int ID_PK { get; set; }
        public int RECORD_FK { get; set; }
        public int SPECIES_FK { get; set; }
        public int SIZE_FK { get; set; }
        public string SPECIES_TEXT { get; set; }
        public string SPECIES_TEXT_2 { get; set; }
        public string TEXT { get; set; }
        public int QUANTITY { get; set; }
        public Nullable<int> QUARANTINE_FK { get; set; }
    
        public virtual MARINE_SPECIES MARINE_SPECIES { get; set; }
        public virtual RECORD_PET_SIZE RECORD_PET_SIZE { get; set; }
        public virtual SHIPMENT_ORDER SHIPMENT_ORDER { get; set; }
    }
}
