//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishInABox.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIPMENT_ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SHIPMENT_ORDER()
        {
            this.SHIPMENT_ITEM = new HashSet<SHIPMENT_ITEM>();
        }
    
        public int ID_PK { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public int SHIPMENT_FK { get; set; }
        public string TEXT { get; set; }
    
        public virtual SHIPMENT SHIPMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHIPMENT_ITEM> SHIPMENT_ITEM { get; set; }
    }
}
