//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishInABox.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TANK_LOG_DAILY
    {
        public int ID_PK { get; set; }
        [Display(Name = "Tank Log ID")]
        public int LOG_FK { get; set; }
        [Display(Name = "Mortality Reason")]
        public int REASON_FK { get; set; }
        [Display(Name = "Quantity")]
        public int QTY { get; set; }
        [Display(Name = "Comment")]
        public string COMMENT { get; set; }
        [Display(Name = "Stuff ID")]
        public Nullable<int> STUFF_FK { get; set; }
        [Display(Name = "Log Date")]
        [DataType(DataType.Date)]
        /* https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.displayformatattribute.dataformatstring(v=vs.110).aspx  */
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public System.DateTime LOG_DATE { get; set; }
    
        public virtual REASON_MORTALITY REASON_MORTALITY { get; set; }
        public virtual TANK_LOG TANK_LOG { get; set; }
        public virtual SYS_STUFF SYS_STUFF { get; set; }
    }
}
