//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishInABox.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TANK
    {
        public int ID_PK { get; set; }
        public int BAY_FK { get; set; }
        public string ID_CODE { get; set; }
        public string TEXT { get; set; }
        public string RFID { get; set; }
    
        public virtual TANK_BAY TANK_BAY { get; set; }
    }
}
