//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishInABox.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TANK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TANK()
        {
            this.TANK_LOG = new HashSet<TANK_LOG>();
        }
    
        public int ID_PK { get; set; }
        [Display(Name = "Bay ID")]
        public int BAY_FK { get; set; }
        [Display(Name = "Tank ID")]
        public string ID_CODE { get; set; }
        [Display(Name = "Tank Description")]
        public string TEXT { get; set; }
        [Display(Name = "RF ID")]
        public string RFID { get; set; }
    
        public virtual TANK_BAY TANK_BAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TANK_LOG> TANK_LOG { get; set; }
    }
}
